// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6FNX0d11oPQN6SMJZsSNFFgDkRq-29ww',
    appId: '1:740356200699:web:117d8009d2d0208faeb85e',
    messagingSenderId: '740356200699',
    projectId: 'mitsumore-app-80c1f',
    authDomain: 'mitsumore-app-80c1f.firebaseapp.com',
    databaseURL: 'https://mitsumore-app-80c1f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mitsumore-app-80c1f.firebasestorage.app',
    measurementId: 'G-56JYV92QBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMmNyqLUgcw5owKoPKmoFLTGaRFfVs7ME',
    appId: '1:740356200699:android:08f5dfc2e852944eaeb85e',
    messagingSenderId: '740356200699',
    projectId: 'mitsumore-app-80c1f',
    databaseURL: 'https://mitsumore-app-80c1f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mitsumore-app-80c1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzlLql0hgrGYVB3VAFdFyMFMioVrdOLac',
    appId: '1:740356200699:ios:7cada2413b269e22aeb85e',
    messagingSenderId: '740356200699',
    projectId: 'mitsumore-app-80c1f',
    databaseURL: 'https://mitsumore-app-80c1f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mitsumore-app-80c1f.firebasestorage.app',
    iosBundleId: 'com.example.mitsumoreAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzlLql0hgrGYVB3VAFdFyMFMioVrdOLac',
    appId: '1:740356200699:ios:7cada2413b269e22aeb85e',
    messagingSenderId: '740356200699',
    projectId: 'mitsumore-app-80c1f',
    databaseURL: 'https://mitsumore-app-80c1f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mitsumore-app-80c1f.firebasestorage.app',
    iosBundleId: 'com.example.mitsumoreAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6FNX0d11oPQN6SMJZsSNFFgDkRq-29ww',
    appId: '1:740356200699:web:577abe705ef9b34daeb85e',
    messagingSenderId: '740356200699',
    projectId: 'mitsumore-app-80c1f',
    authDomain: 'mitsumore-app-80c1f.firebaseapp.com',
    databaseURL: 'https://mitsumore-app-80c1f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mitsumore-app-80c1f.firebasestorage.app',
    measurementId: 'G-W6GVCSZPT3',
  );

}